### ISSUE TITLE
Sometimes Appium can't start browser: "Cannot read property 'ELEMENT' of undefined"

### ISSUE THREAD

**Issue by midopa** [appium/appium-ios-driver#182]
```
2016-09-09 20:45:24:682 - [MJSONWP] Encountered internal error running command: TypeError: Cannot read property 'ELEMENT' of undefined
```

This happens many times and randomly. All I'm doing is starting a new Appium session from scratch (`new IOSDriver<>(capabilities)`) with the following capabilities:

Capabilities:
* showIOSLog: true
* noReset: false
* sendKeyStrategy: 'grouped'
* newCommandTimeout: 1000000
* platformVersion: '9.3'
* safariAllowPopups: true
* automationName: 'WebDriverAgent'
* browserName: 'safari'
* platformName: 'iOS'
* deviceName: 'iPad Air'

Environment:
* OSX El Capitan 10.11.6
* Node 6.5.0
* Appium 1.5.3
* Appium Java client 3.4.1
* XCode 7

[Full stack trace](https://gist.github.com/midopa/ec3656377caf6bb73ea7b7010069288d)
[Appium logs](https://gist.github.com/midopa/3933896cdf439382995dfeb396df8e7c)

**Comment by imurchie** [comment]
This is fixed in `appium-ios-driver@1.12.25`

**Comment by midopa** [comment]
I cherry picked the change onto Appium 1.5.3 and iOS driver 1.12.2 (since I'm not ready to move to XCUITest stuff).

I'll still seeing the issue. It looks like this is the basic flow:

1. Look for URL bar ✔️ 
1. Tap URL bar ❌ 
    1. Now the code goes into the catch, where a new page will be opened
1. Look for text field ❌ 

I'm thinking this issue is related to the refresh.

**Comment by midopa** [comment]
I'm testing a change that repeats the steps 1-3 in a mini loop.

**Comment by midopa** [comment]
Oops!!! Nevermind, the problem was I was using XCode 8 beta's simulator!
